#!/bin/bash
clear
echo "This bootstrap script assumes a minimal arch install and will handle all dependencies"
echo "such as x11, video and audio drivers, default configs for apps, and install apps either"
echo "integral to the experience, or that I personally believe are worthy to make the cut."
echo ""
echo ""
echo "Please review this script before running and understand what is being installed, how, and to where."
echo "RUN THIS SCRIPT AT YOUR OWN RISK!"
read -p "Would you like to continue? (Y/n): " -r answer
answer=${answer:-Y}
[[ "$answer" =~ ^[Yy]$ ]] || exit 1
echo "Excellent. Continuing bootstrap..."
sleep 5s
clear
echo "Installing Audio & Video..."
sudo pacman -Sy
sudo pacman -S xorg-server xorg-xinit intel-media-driver libva-intel-driver mesa vulkan-intel vulkan-nouveau vulkan-radeon xf86-video-amdgpu xf86-video-ati xf86-video-nouveau pipewire pipewire-pulse wireplumber
clear
echo "Installing Prereqs..."
sudo pacman -S --needed git base-devel xorg-xfd ttf-bigblueterminal-nerd alacritty starship rofi thunar eza vim
mkdir -p ~/.src
clear
echo "Installing YaY"
cd ~/.src
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
clear
echo "Installing PreReqs from AUR..."
echo "WHEN PROMPTED, PLEASE SELECT pipewire-jack"
read -p "Do you understand and would like to continue? (Y/n): " -r answer
answer=${answer:-Y}
[[ "$answer" =~ ^[Yy]$ ]] || exit 1
yay -S nordic-theme nordzy-icon-theme nordzy-cursors librewolf-bin light fish fastfetch pavucontrol
clear
echo "Intalling Rustup..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >> ./rustup.sh
chmod +x ./rustup.sh
source ./rustup.sh
source ~/.bashrc
export PATH="$HOME/.cargo/bin:$PATH"
rm ./rustup.sh
clear
echo "Installing extras..."
cd ~/.src
source ~/.bashrc
echo "Building rdir..."
git clone https://github.com/sigvaldr/rdir.git
cd rdir
cargo build --release
echo "Installing rdir..."
sudo cp target/release/rdir /usr/bin/
clear
echo "Buildilng boxr..."
cd ~/.src
git clone https://github.com/sigvaldr/boxr.git
cd boxr
cargo build --release
echo "Installing boxr..."
sudo cp target/release/boxr /usr/bin
sudo cp target/release/unboxr /usr/bin
clear
echo "Requirements installed"
echo "Configuring groups and services..."
sudo usermod -aG audio $USER
sudo usermod -aG video $USER
sudo systemctl enable pipewire.service
sudo systemctl enable pipewire-pluse.service
sudo systemctl enable wireplumber.service
clear
echo "Building SIGWM..."
cd ~/.src
git clone https://github.com/sigvaldr/sigwm.git
cd sigwm
cargo build --release
sudo cp target/release/sigwm /usr/bin
echo "Applying Default Themes & Configs..."
cp -R .config ~/
cp .xinitrc ~/
echo "Switching to fish shell..."
echo "Please type /usr/bin/fish when asked for new shell"
echo ""
echo ""
chsh
echo ""
echo "-----------------------------------"
echo "Installation complete."
echo "Please reboot into your new WM :)"
echo "-----------------------------------"
