[package]
name = "sigwm"
version = "0.1.1"
edition = "2024"
authors = ["Sigvaldr Nótthrafn - me@sigvaldr.lol"]
repository = "https://github.com/sigvaldr/sigwm"
description = "Custom WM"
license = ""
readme = "README.md"
keywords = []
categories = []


[dependencies]
penrose = "0.4.0"
penrose_ui = "0.4.0"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
